# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\Dede\Workshop\things\uni\vj\vj_practicas\ice climbers (nes)"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\Dede\Workshop\things\uni\vj\vj_practicas\ice climbers (nes)"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Dede\Workshop\things\uni\vj\vj_practicas\ice climbers (nes)\CMakeFiles" "D:\Dede\Workshop\things\uni\vj\vj_practicas\ice climbers (nes)\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Dede\Workshop\things\uni\vj\vj_practicas\ice climbers (nes)\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

Assets/Scripts/Cloud.obj: Assets/Scripts/Cloud.cpp.obj
.PHONY : Assets/Scripts/Cloud.obj

# target to build an object file
Assets/Scripts/Cloud.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Cloud.cpp.obj
.PHONY : Assets/Scripts/Cloud.cpp.obj

Assets/Scripts/Cloud.i: Assets/Scripts/Cloud.cpp.i
.PHONY : Assets/Scripts/Cloud.i

# target to preprocess a source file
Assets/Scripts/Cloud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Cloud.cpp.i
.PHONY : Assets/Scripts/Cloud.cpp.i

Assets/Scripts/Cloud.s: Assets/Scripts/Cloud.cpp.s
.PHONY : Assets/Scripts/Cloud.s

# target to generate assembly for a file
Assets/Scripts/Cloud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Cloud.cpp.s
.PHONY : Assets/Scripts/Cloud.cpp.s

Assets/Scripts/Controllers.obj: Assets/Scripts/Controllers.cpp.obj
.PHONY : Assets/Scripts/Controllers.obj

# target to build an object file
Assets/Scripts/Controllers.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Controllers.cpp.obj
.PHONY : Assets/Scripts/Controllers.cpp.obj

Assets/Scripts/Controllers.i: Assets/Scripts/Controllers.cpp.i
.PHONY : Assets/Scripts/Controllers.i

# target to preprocess a source file
Assets/Scripts/Controllers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Controllers.cpp.i
.PHONY : Assets/Scripts/Controllers.cpp.i

Assets/Scripts/Controllers.s: Assets/Scripts/Controllers.cpp.s
.PHONY : Assets/Scripts/Controllers.s

# target to generate assembly for a file
Assets/Scripts/Controllers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Controllers.cpp.s
.PHONY : Assets/Scripts/Controllers.cpp.s

Assets/Scripts/Player.obj: Assets/Scripts/Player.cpp.obj
.PHONY : Assets/Scripts/Player.obj

# target to build an object file
Assets/Scripts/Player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Player.cpp.obj
.PHONY : Assets/Scripts/Player.cpp.obj

Assets/Scripts/Player.i: Assets/Scripts/Player.cpp.i
.PHONY : Assets/Scripts/Player.i

# target to preprocess a source file
Assets/Scripts/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Player.cpp.i
.PHONY : Assets/Scripts/Player.cpp.i

Assets/Scripts/Player.s: Assets/Scripts/Player.cpp.s
.PHONY : Assets/Scripts/Player.s

# target to generate assembly for a file
Assets/Scripts/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/Assets/Scripts/Player.cpp.s
.PHONY : Assets/Scripts/Player.cpp.s

Libraries/engine/EngineECS.obj: Libraries/engine/EngineECS.cpp.obj
.PHONY : Libraries/engine/EngineECS.obj

# target to build an object file
Libraries/engine/EngineECS.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/EngineECS.cpp.obj
.PHONY : Libraries/engine/EngineECS.cpp.obj

Libraries/engine/EngineECS.i: Libraries/engine/EngineECS.cpp.i
.PHONY : Libraries/engine/EngineECS.i

# target to preprocess a source file
Libraries/engine/EngineECS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/EngineECS.cpp.i
.PHONY : Libraries/engine/EngineECS.cpp.i

Libraries/engine/EngineECS.s: Libraries/engine/EngineECS.cpp.s
.PHONY : Libraries/engine/EngineECS.s

# target to generate assembly for a file
Libraries/engine/EngineECS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/EngineECS.cpp.s
.PHONY : Libraries/engine/EngineECS.cpp.s

Libraries/engine/EngineUI.obj: Libraries/engine/EngineUI.cpp.obj
.PHONY : Libraries/engine/EngineUI.obj

# target to build an object file
Libraries/engine/EngineUI.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/EngineUI.cpp.obj
.PHONY : Libraries/engine/EngineUI.cpp.obj

Libraries/engine/EngineUI.i: Libraries/engine/EngineUI.cpp.i
.PHONY : Libraries/engine/EngineUI.i

# target to preprocess a source file
Libraries/engine/EngineUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/EngineUI.cpp.i
.PHONY : Libraries/engine/EngineUI.cpp.i

Libraries/engine/EngineUI.s: Libraries/engine/EngineUI.cpp.s
.PHONY : Libraries/engine/EngineUI.s

# target to generate assembly for a file
Libraries/engine/EngineUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/EngineUI.cpp.s
.PHONY : Libraries/engine/EngineUI.cpp.s

Libraries/engine/raylibx.obj: Libraries/engine/raylibx.cpp.obj
.PHONY : Libraries/engine/raylibx.obj

# target to build an object file
Libraries/engine/raylibx.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/raylibx.cpp.obj
.PHONY : Libraries/engine/raylibx.cpp.obj

Libraries/engine/raylibx.i: Libraries/engine/raylibx.cpp.i
.PHONY : Libraries/engine/raylibx.i

# target to preprocess a source file
Libraries/engine/raylibx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/raylibx.cpp.i
.PHONY : Libraries/engine/raylibx.cpp.i

Libraries/engine/raylibx.s: Libraries/engine/raylibx.cpp.s
.PHONY : Libraries/engine/raylibx.s

# target to generate assembly for a file
Libraries/engine/raylibx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\engine.dir\build.make CMakeFiles/engine.dir/Libraries/engine/raylibx.cpp.s
.PHONY : Libraries/engine/raylibx.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... engine
	@echo ... main
	@echo ... Assets/Scripts/Cloud.obj
	@echo ... Assets/Scripts/Cloud.i
	@echo ... Assets/Scripts/Cloud.s
	@echo ... Assets/Scripts/Controllers.obj
	@echo ... Assets/Scripts/Controllers.i
	@echo ... Assets/Scripts/Controllers.s
	@echo ... Assets/Scripts/Player.obj
	@echo ... Assets/Scripts/Player.i
	@echo ... Assets/Scripts/Player.s
	@echo ... Libraries/engine/EngineECS.obj
	@echo ... Libraries/engine/EngineECS.i
	@echo ... Libraries/engine/EngineECS.s
	@echo ... Libraries/engine/EngineUI.obj
	@echo ... Libraries/engine/EngineUI.i
	@echo ... Libraries/engine/EngineUI.s
	@echo ... Libraries/engine/raylibx.obj
	@echo ... Libraries/engine/raylibx.i
	@echo ... Libraries/engine/raylibx.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

